### PR TITLE
Update #1

### PR DESCRIPTION
**Pull request by KranKRival**
1.Added Horison OS version Show
2.Added Atmosphere version Show

### CODE REVIEW

**Comment by ITotalJustice** [comment]
Thank you very much for this. Code looks good too!

I noticed that you called this update 1. Did you plan to add more to this pr?

**Comment by KranKRival** [comment]
hmm not to this pr but maybe in next pr's

**Comment by KranKRival** [comment]
i just have many things to do and many plans.
that's it for now :P

**Comment by ITotalJustice** [comment]
> i just have many things to to and many plans.
> that's it for now :P

That's fine. Just wanted to be sure before accepting the pr 😄

**Comment by KranKRival** [comment]
yeah , that's always good to be sure :P

**Comment by KranKRival** [comment]
also check discord ive posted a pic in 4TU channel

**Pull request merged**
